version: '3.9'
volumes:
  mysql:
    driver: local
  wordpress:
    driver: local

services:
  wp:
    container_name: wp
    image: wordpress:latest
    restart: always
    working_dir: /var/www/html
    ports:
      - '8080:80'
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html
    environment:
      TZ: 'Asia/Tokyo'
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: 'wordpress'
      WORDPRESS_DB_PASSWORD: 'wordpress'
      WORDPRESS_DB_NAME: 'wordpress_db'
      WORDPRESS_DEBUG: 1
  db:
    container_name: db
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'wordpress_db'
      MYSQL_ROOT_PASSWORD: 'wordpress'
      MYSQL_USER: 'wordpress'
      MYSQL_PASSWORD: 'wordpress'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db
